### ISSUE TITLE
Not possible to delete users from Dashboard

### ISSUE THREAD

**Issue by hyperknot** [supabase/supabase#11122]
# Bug report

## Describe the bug

It is not possible to delete users from Dashboard.

## To Reproduce

1. Make a new project.
2. Run "User Management Starter" SQL.
3. Invite a user
4. Delete the user on the Dashboard ...
<img width="309" alt="image" src="https://user-images.githubusercontent.com/494223/208668885-c3d15b3b-ae81-462a-949b-dfa7ce2453b2.png">

Error, request's content:
```
{"message":"Failed to delete user","errorEventId":"00000000000000000000000000000000"}
```

## Expected behavior

User should be deleted

## Screenshots

<img width="380" alt="image" src="https://user-images.githubusercontent.com/494223/208668926-847e64b8-5375-4690-b6f6-df8ee52201ff.png">

## System information

Web dashboard

**Comment by saltcod** [comment]
Hey @hyperknot — does that user own data in any tables?

**Comment by hyperknot** [comment]
No, I just click invite, signup and that's it. You can reproduce this only with the 4 clicks I mentioned.

**Comment by hyperknot** [comment]
It doesn't even need to click the link in the invitation email, enough to invite + delete.

**Comment by saltcod** [comment]
I just ran through the User Management Starter and I think it does have to do with content in a table. 
When you run that SQL, it creates a `profiles` table and adds an entry to it. Since the invited user "owns" that entry, you can't delete it. If you delete their entry in the `profiles` table, you should be able to remove that user.

**Comment by kiwicopple** [comment]
perhaps you have a trigger on the auth.users table @hyperknot ? one that creates data in another table?

**Comment by hyperknot** [comment]
Then an ON DELETE CASCADE is missing somewhere, or something similar. I mean it's pretty much buggy if I click 2 buttons to create a sample project and then I cannot delete users.

**Comment by hyperknot** [comment]
@kiwicopple I don't have anything in any table, I just run the official "User Management Starter" SQL which is basically the foundation of every tutorial on this site.

**Comment by hyperknot** [comment]
I _think_ adding an ON DELETE CASCADE to this line might solve this:

```
create table profiles (
  id uuid references auth.users not null primary key,
```

**Comment by baststar** [comment]
i just ran into this issue:
i tried to delete the row via phpstorm that gives me this error:
ERROR: update or delete on table "users" violates foreign key constraint "objects_owner_fkey" on table "objects"

Ah! There are avatars stored to the user!

ON DELETE CASCADE would help!

**Comment by Hallidayo** [comment]
I've just tried `ON DELETE CASCADE` in the starter queries and this does work on a local instance I have.

@saltcod - I can create a pull if needed?

**Comment by saltcod** [comment]
Nice! Would be great @Hallidayo thank you!

**Comment by GaryAustin1** [comment]
Be careful here, there are two subjects now.  One is the starter example and profile delete cascade.  The other is @baststar and mentioning the storage object table tied to auth.users thru owner.  

You can not just delete cascade the object table, unless Supabase adds a delete trigger function to also delete the s3 file data, or you will orphan files.

**Comment by joshenlim** [comment]
marking this issue as resolved with this PR going in https://github.com/supabase/supabase/pull/11135

as @GaryAustin1 mentioned regarding the storage side of things - that'll be a separate issue, so feel free to create another one!

**Comment by madipta** [comment]
don't know if same issue

I can not delete user from dashboard because delete button is missing from users table

**Comment by GitTorres** [comment]
This just happened to me as well when I tried to create a user via an invite.  Send invite then immediately attempted to delete. I got around it by first clicking "Remove MFA Factors" for the user.  Then the delete worked.  Hope this helps someone else in this situation.

**Comment by enricovara** [comment]
I still have this issue as well

<img width="386" height="177" alt="Image" src="https://github.com/user-attachments/assets/c00b07cc-1875-484b-b6f2-a617389740e0" />

**Comment by GaryAustin1** [comment]
@enricovara Check your Postgres logs in the dashboard.  You likely have some other table with a foreign key pointing to auth.users and the row pointing to this user has to be deleted first.  You can also set the foreign key constraint up as cascade to have it auto delete.  It could also be you have a delete trigger on auth.users failing.
