### ISSUE TITLE
`DROP DATABASE` times out

### ISSUE THREAD

**Issue by janpio** [supabase/supabase#11691]
I am currently investigating the Prisma + Supabase problems when trying to use migrate dev (reported on our side at https://github.com/prisma/prisma/issues/17160 or https://github.com/prisma/prisma/issues/16853). The error message we know about is `ERROR: canceling statement due to statement timeout`. It is thrown during the migration process, probably when we do shadow database related things (we create a database in the background, apply our previous migrations, compare that to the main database, then drop the newly created database again).

While trying to understand what might be going on there, I also created a few databases manually (as also recommended [in your docs](https://supabase.com/docs/guides/integrations/prisma#configuring-the-project-to-use-postgresql)) - and then tried to drop them again. Creation works fine (`CREATE DATABASE example;`), but it seems dropping them (`DROP DATABASE example;`) runs into the same timeout error:

```
  InvocationTargetException
  java.lang.reflect.InvocationTargetException
    SQL Error [08001]: Connection attempt timed out.
      Connection attempt timed out.
```     
(Error message from DBeaver, a Java based database GUI I used to make sure my testing is not influenced by Prisma)
(Often a tiny bit later the connection to the database is also killed)

I could reproduce this behavior even in cases where we cerate a new Supabase project, and then only ran these two queries:

```sql
CREATE DATABASE foo;
DROP DATABASE foo;
```

Seems something is blocking `DROP DATABASE` on databases of new projects.

**Comment by pcnc** [comment]
Hi @janpio 

We've managed to confirm the issue - it seems to be due to a new ProcSignalBarrier mechanism introduced in PG15, which hasn't been implemented in some of our extensions.

`DROP DATABASE` emits a signal and waits for other backends (some of which are opened by extensions) to accept it, whereas the backends wait for the `DROP DATABASE` query to finish executing, leading to a deadlock and thus, to a timeout.

We're discussing this internally and hoping to quickly find a solution for this issue.

**Comment by HugoRamonPereira** [comment]
I am having the same problem, Prisma and Supabase, I already executed the command to reset the database and I am trying to create a new migration but my attempts have been unsuccessful... 

I am using the command (npx prisma migrate dev --name first-migration) 
and it says: 
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at...  

and it doesn't work, it doesn't show the message (Your database is now in sync with your schema) neither it confirms that it has generated the Prisma Client..

What it does is the following: I get an error:
Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:269

**Comment by samdigitalpanda** [comment]
> I am having the same problem, Prisma and Supabase, I already executed the command to reset the database and I am trying to create a new migration but my attempts have been unsuccessful...
> 
> I am using the command (npx prisma migrate dev --name first-migration) and it says: Prisma schema loaded from prisma/schema.prisma Datasource "db": PostgreSQL database "postgres", schema "public" at...
> 
> and it doesn't work, it doesn't show the message (Your database is now in sync with your schema) neither it confirms that it has generated the Prisma Client..
> 
> What it does is the following: I get an error: Error: db error: ERROR: canceling statement due to statement timeout 0: migration_core::state::DevDiagnostic at migration-engine/core/src/state.rs:269

A workaround for this is detailed in  [this issue thread](https://github.com/prisma/prisma/issues/17160) until supabase figure out the DROP DATABASE issues on their end

**Comment by pcnc** [comment]
Hello everybody,

We've been tracking this in https://github.com/supabase/pg_net/issues/78.
The issue has been solved in pg_net 0.7 ([PR](https://github.com/supabase/pg_net/pull/81)) and we'll be rolling this out for new projects in the days to follow.

We're aiming to roll this out to existing projects within the next few weeks.

**Comment by pcnc** [comment]
Hello everybody,

We've merged this in

**Comment by pcnc** [comment]
Hello everybody - we've released pg_net 0.7 to the Supabase platform, which fixes this issue.

This is now available for any new project, or to any project that is paused and then unpaused.
As for existing projects which can't afford to be paused, or cannot be paused, we're working on our strategy to update them in the weeks to come - will update here when we roll this out.

**Comment by janpio** [comment]
Has this roll out happened yet? We are waiting for confirmation on the Prisma side to close our https://github.com/prisma/prisma/issues/17160.

**Comment by pcnc** [comment]
We've rolled out pg_net 0.7 on the 26th of January - strategy to roll this out to existing projects is still pending.
Existing projects can pause + unpause to update to the latest pg_net version; paid projects unfortunately have to create a support ticket for the time being.

@fruttasecca I can take a closer look at your project - feel free to create a support ticket and reference this issue.

**Comment by fruttasecca** [comment]
Hi @pcnc , thanks for the quick reply, will followup with a support ticket if necessary

**Comment by zachblume** [comment]
This problem is still present in local development via `supabase start` and then running CREATE DATABASE foo;DROP DATABASE foo; via psql. pg_net was never turned on.

**Comment by zachblume** [comment]
> This problem is still present in local development via `supabase start` and then running CREATE DATABASE foo;DROP DATABASE foo; via psql. pg_net was never turned on.

I just confirmed that the issue is not present in hosted supabase, only local development.

**Comment by zachblume** [comment]
Nevermind :) I upgrade the CLI from 1.27 to current 1.43 and now everything works.
```
brew install supabase
mkdir supabase-bug-fixed
cd supabase-bug-fixed
supabase init
supabase start
echo "a"
psql "postgresql://postgres:postgres@localhost:54322/postgres" -c "CREATE DATABASE foo;"
echo "b"
psql "postgresql://postgres:postgres@localhost:54322/postgres" -c "DROP DATABASE foo;"
echo "c"
```
Succeeds whereas fails in CLI 1.27
