### ISSUE TITLE
code: 429, msg: "Email rate limit exceeded" with custom SMTP mailjet

### ISSUE THREAD

**Issue by ProfiroiuMihai** [supabase/supabase#16031]
I have a paid membership with a custom smtp enabled and still have the problem.
 It was working yesterday today is not working.

Giving me :
{code: 429, msg: "Email rate limit exceeded"}

Simmilar to this closed issue. https://github.com/supabase/supabase/issues/10850

I have mailjet premium configured that has 50000 emails but still does not work.
![image](https://github.com/supabase/supabase/assets/44637696/0c07790d-6dbc-4b58-89bd-35ba06645a98)

**Comment by ProfiroiuMihai** [comment]
Simmilar to this closed issue. https://github.com/supabase/supabase/issues/10850

**Comment by hawkcookie** [comment]
I have the same problem. Like the issued description,  it worked well yesterday, but today it does not.

**Comment by Huge-Puppy** [comment]
I'm also getting this error on email signup. Just started occurring. Signed up for a paid plan as I thought it might be that my free account was rate limited. Still broken.

**Comment by monicakh** [comment]
Sorry for the inconvenience you're experiencing. We've already notified our Auth team, and they have a fix lined up in the queue.

**Comment by monicakh** [comment]
The fix has been rolled out to all affected projects.

**Comment by devtanna** [comment]
Hello, I am still encountering this issue.
I get a `AuthApiError: Internal server error` when using mailjet as a SMTP provider

**Comment by Sqrrl** [comment]
Having the same issue using resend.com. Operations sending out emails fail with something like this:
```
"Error sending recovery email: gomail: could not send email 1: 450 Cannot read properties of undefined (reading 'text')
```

It was working fine before.

**Comment by hawkcookie** [comment]
@monicakh 

Thank you, it seems that the issue has been resolved. However, I am concerned about the potential implications if this issue were to occur in a production environment. If this authentication problem were to reoccur, users could be unable to sign up or log in for an extended period. If it does happen, what immediate actions could we take to ensure minimal disruption to our users?

**Comment by hichana** [comment]
I'm getting this same error without using mailjet and just trying password reset

**Comment by kangmingtay** [comment]
Hey everyone! we've already pushed out the fix for this - if you're still experiencing rate limit issues with custom SMTP enabled - please send us a support ticket at https://app.supabase.com/support/new. It would be much easier for us to look into these problems specifically. 

@hawkcookie unfortunately this was one of those issues that had to be resolved on our end internally. we don't have a workaround for you to prevent this from happening but we've added a bunch of internal tests to make sure that it doesn't happen again. 

The issue was due to a check we had internally to set the rate limit env var on your project's auth service. There was an issue with the check to detect if a project was using custom SMTP or not. Because the check was buggy, it resulted in a number of false negatives and ended up setting the default rate limit on those projects instead of the one you specified.

**Comment by emmaudeji** [comment]
I am still facing this issue today. I don't have any SMTP configured. Justing testing my app locally with the default email setting.

{
    "error": {
        "name": "AuthApiError",
        "message": "Email rate limit exceeded",
        "status": 429
    }
}

**Comment by ben-pacingagency** [comment]
I am having this issue - configured resend via SMTP and it was working fine for a few hours....

now seeing this error..

      "msg": "429: email rate limit exceeded"


I've only tried like 10 login attempts in the last hour! Not exactly a lot
