### ISSUE TITLE
React Native .from().select() promise never resolves in release (Expo)

### ISSUE THREAD

**Issue by He1nr1chK** [supabase/supabase#1693]
# Bug report

## Describe the bug

When testing the from().select() function in debug mode in an ejected Expo app the data is returned successfully, however, once you switch to the release variant, nothing is returned. The app does not crash meaning no major errors are being thrown. 

## To Reproduce

```
const { data, error } = await supabase
      .from('table')
      .select('*')
      .eq('column', variableToMatch);
```

## Expected behavior

The expected behaviour is that the call will return the requested data from the Supabase table or an error suggesting that something went wrong.

## System information

- OS: macOS
- Version of supabase-js: v1.11.12
- Version of Node.js: v14.16.0
- Version of Async Storage: v1.15.4
- Version of Expo: v41.0.0
- Version of React Native: v0.63.4

## Additional context

I have been getting these logs: `Error getting session from URL.`, `nw_socket_handle_socket_event [C5:1] Socket SO_ERROR [61: Connection refused]`, `nw_connection_get_connected_socket [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection`, `TCP Conn 0x2806304d0 Failed : error 0:61 [61]`, `SocketRocket: In debug mode. Allowing connection to any root cert` but I am uncertain whether the last four pertain to Supabase. Happens on both Android and iOS.

**Comment by He1nr1chK** [comment]
Upon further investigation I have been able to narrow it down to the promise never resolving. @kiwicopple @awalias, what are your thoughts on this?

**Comment by kiwicopple** [comment]
Great debugging @He1nr1chK  - I think it's related to `cross-fetch`:

https://github.com/supabase/postgrest-js/blob/e14461cb752e603c6dca9ca114bc882a3b137636/package.json#L33

Perhaps this isn't supported in ReactNative environments? 

https://stackoverflow.com/questions/52917733/cross-fetch-doesnt-work-with-react-native

Although I thought this was patched already: https://github.com/lquixada/cross-fetch/issues/26

We have to Ponyfill [CloudflareWorkers](https://github.com/supabase/supabase/tree/master/examples/with-cloudflare-workers), and perhaps we need to do something similar with RN?

**Comment by He1nr1chK** [comment]
Hi @kiwicopple, thanks for getting back to me. Do you think it might be linked somehow to the fix of adding `import 'react-native-url-polyfill/auto';` to `index.js`? Maybe the two might not work correctly together or maybe polyfill as a whole does not work with RN and the workaround of adding the import merely suppresses the symptom without actually solving the problem?

**Comment by Hannes1** [comment]
This is weird behaviour because fetch is working for gotrue-js in production (creating users and signin) but not for postgres-js as the ` await supabase` never gets resolved. Cross-fetch uses: [fetch](https://github.com/github/fetch)  package for the react native environment, maybe some fetch feature not supported? But in development getting or updating  works fine.

**Comment by He1nr1chK** [comment]
@kiwicopple, I noticed that Gotrue Client uses `cross-fetch` as well and it seems to work in production which is odd. Thus I doubt that `cross-fetch` by itself is the culprit. What do you do differently when it comes to network requests between the two?

**Comment by kiwicopple** [comment]
OK one other idea:

> Error getting session from URL.,

that looks like it's getting thrown from [here](https://github.com/supabase/gotrue-js/blob/9ad7b524e76c9111b19b6ea27ee12108e63ac34a/src/GoTrueClient.ts#L82)

Are you using OAuth logins?

Perhaps:

- the session isn't saved to LocalStorage (on a native device)
- tries to make a fetch with no session -> data not returned ?

Are you overriding local storage in your Expo app? 
https://github.com/supabase/gotrue-js/blob/9ad7b524e76c9111b19b6ea27ee12108e63ac34a/src/GoTrueClient.ts#L62

If yes, which js libary are you using? Same as the examples here:
https://github.com/supabase/supabase/blob/23cac64b0c40ab9421108eb830d1b7b35979bd32/examples/expo-todo-list/package.json#L11

**Comment by He1nr1chK** [comment]
I am using `@react-native-async-storage/async-storage: ^1.15.4`.  
```
import { createClient } from '@supabase/supabase-js';
import AsyncStorage from '@react-native-async-storage/async-storage';

const supabase = createClient(supabaseURL, supabaseAnon, {
  localStorage: AsyncStorage as any,
  persistSession: true,
  autoRefreshToken: true
});
```
Does `postgrest-js` require a session before making a request?

**Comment by He1nr1chK** [comment]
No but that can't be it either because I am calling the function by passing the user object to it. So the user and session are valid when I make the call. I am really at a loss as to why this is happening.

**Comment by He1nr1chK** [comment]
My cofounder is of the opinion that the issue arises in _getAuthHeaders in supabase-js/src/SupabaseClient.ts line 82 here: 
```
from<T = any>(table: string): SupabaseQueryBuilder<T> {    
    const url = `${this.restUrl}/${table}`    
    return new SupabaseQueryBuilder<T>(url, {     
        headers: this._getAuthHeaders(),      
        schema: this.schema,      
        realtime: this.realtime,      
        table,    
    })  
}
```

**Comment by kiwicopple** [comment]
hmm if that's the case, these errors:

![image](https://user-images.githubusercontent.com/10214025/119977955-9ac8c200-bfeb-11eb-8a31-e67e42dbf90a.png)

suggest either:

- `${this.restUrl}/${table}`  is a invalid var, and so when it's trying to init it is failing because it's trying to connect to `undefined`
- `${this.restUrl}/${table}`  is a valid var, and it can't init for another reason - perhaps websockets are being difficult on RN?

What would be the minimum steps to replicated this? Do i need to publish it all the way to the app store to see this error?

**Comment by He1nr1chK** [comment]
No the appstore isn't necessary. I believe you could just use the expo example and run `expo eject` in the directory after configuring the `app.json`. Once you have done that you should be able to run the ejected app in Xcode or Android Studio or the terminal using `react-native run-android/run-ios`. Now that I think about it, Websockets might be the culprit because I remember that we initially had some issues with Websockets and RN before we switched to gRPC.

**Comment by He1nr1chK** [comment]
@kiwicopple, it appears that you are using the package `Websocket-Node` for the realtime client. It is likely that this specific package does not support React Native right out of the box as it seems to be aimed exclusively at browsers.

**Comment by He1nr1chK** [comment]
@kiwicopple how do I test the package if I want to make some changes? Meaning how do I bundle it together with the other packages to test?

**Comment by soedirgo** [comment]
Hey @He1nr1chK, I tried reproducing this locally with `expo-todo-list` and don't see the error you mentioned here. The only extra steps I did was some fudging with the Podfile because the Flipper version was out of date.

Can you create a minimal reproducible example repo that exhibits the issue? It'd help if you can still reproduce it in plain React Native, as `expo eject` is rather finnicky in M1 Macs. It'd help even more if you could reduce it to the specific clients (realtime-js/postgrest-js)—[here's](https://github.com/supabase/realtime-js/tree/master/example) a small example of listening to Supabase through realtime-js directly, and for postgrest-js you can try doing a simple `from().select()` on top of a vanilla `expo init`.

**Comment by He1nr1chK** [comment]
Hi @soedirgo, did you change the `Build Configuration` to `Release` before testing in Xcode? The issue only seems to come up in the Release variant.

**Comment by manfredwedderin** [comment]
He1nr1chK ***@***.***> schrieb am Fr., 4. Juni 2021, 15:18:

**Comment by soedirgo** [comment]
Yup, here's my attempt:

https://user-images.githubusercontent.com/31685197/120826147-b3f1e580-c58c-11eb-991e-d21ac516f7e2.mp4

**Comment by He1nr1chK** [comment]
Hi @soedirgo, yeah no you are still running in debug. To run in `Release` you have to run `expo publish` in your project directory after configuring your `app.json` and then in Xcode click on your project name next to the device selection in the top right corner. This will bring up a dialog, click `Edit Scheme`. In the `Run` tab change the `Build Configuration` to `Release`

**Comment by soedirgo** [comment]
Same thing here:

https://user-images.githubusercontent.com/31685197/120835964-9aa26680-c597-11eb-8b26-3d3a0f569dbd.mp4

I'm not sure if I can keep debugging it like this without further leads/minimal example—in all likelihood this is a RN issue, I'm not fluent in RN/Expo (what goes in app.json?), and it takes a lot of effort just to get the `expo eject`ed project to build (this time I had to wrangle with watchman and missing main.jsbundle).

**Comment by He1nr1chK** [comment]
After many wasted hours @Hannes1 figured out that `react-native-url-polyfill` was the culprit. We were using the latest version but when we downgraded to `v1.2.0` the promises were getting resolved. Thanks @soedirgo and @kiwicopple for the help. Love your product btw, plan on using it for my personal projects into the foreseeable future.

**Comment by soedirgo** [comment]
Glad the issue is resolved @He1nr1chK, that was hard to nail down... Not the first issue with `URL` in RN, and won't be the last 😄

**Comment by kiwicopple** [comment]
Thanks for working so hard on this @He1nr1chK 🙏 . And thanks for coming back with an update

> react-native-url-polyfill was the culprit. We were using the latest version but when we downgraded to v1.2.0 the promises were getting resolved

Is this a bug with `react-native-url-polyfill`, or is this something that we should be fixing on our side to ensure it's compatible with the latest version?

**Comment by He1nr1chK** [comment]
@kiwicopple honestly have no idea, never really looked into how (or why) `react-native-url-polyfill` works.

**Comment by davitykale** [comment]
Is anyone still experiencing this? I get the "Error getting session from URL." every single time. 

Based on the previous comments, I'm using the following versions of these libraries:

```
"@supabase/supabase-js": "^1.18.1",
"@react-native-async-storage/async-storage": "^1.15.4",
"react-native-url-polyfill": "1.2.0",
```

**Comment by soedirgo** [comment]
Can you create a new issue @davitykale? Also if you can create a repo as a minimal reproducible example, perhaps using the [expo-todo-list](https://github.com/supabase/supabase/tree/master/examples/expo-todo-list) example as a template, that'd be great - debugging Expo/RN was a bit of a pain to set up 😅

**Comment by 10000multiplier** [comment]
@davitykale @soedirgo in expo sdk 43 the app won't even compile.

**Comment by Hannes1** [comment]
> @davitykale @soedirgo in expo sdk 43 the app won't even compile.

@10000multiplier I'm currently using supabase with sdk43 it works fine👍

**Comment by 10000multiplier** [comment]
@Hannes1 can you please try running https://github.com/supabase/supabase-js/issues/295?

I'm very interested in how you got it to work.

**Comment by Hannes1** [comment]
@10000multiplier do note I'm still using supabase 1.13.2

**Comment by 10000multiplier** [comment]
> @10000multiplier do note I'm still using supabase 1.13.2

The example doesn't work with 1.13.2 either.

Are you perhaps doing anything differently?

**Comment by tonyneel** [comment]
I also have this issue. Should this actually be closed? I am going to see if rolling back url-polyfill fixes my issue but I think most people using supabase and RN will run into this.

**Comment by soedirgo** [comment]
@tonyneel can you create a separate issue, ideally with a reproduction repo like [this](https://github.com/supabase/supabase-js/issues/295#issue-1040714664)? The issue in that link should have been fixed, and this issue was on the url polyfill side.

We should probably add a note about this on the [docs](https://supabase.com/docs/reference/javascript/installing) though.

**Comment by tonyneel** [comment]
> 

It turns out upgrading react native fixed this issue. Sorry for the red herring.
