### ISSUE TITLE
Bug: to add auth hooks to customize the token

### ISSUE THREAD

**Issue by thibault-chausson** [supabase/supabase#20280]
## Description
I am using the free version on SupaBase and the online [tutorial](https://supabase.com/docs/guides/auth/auth-hooks?language=add-admin-role) states that we can add hooks to customize the token, but it does not work when I try to add them. Attached is a screenshot of the tutorial and my Supabase page for editing the hooks.
Thank you for your help :pray::pray:!

## Tutorial 
<img width="812" alt="Capture d’écran 2024-01-09 à 19 23 32" src="https://github.com/supabase/supabase/assets/82728820/b5146345-3543-4d1b-95fb-c95daef63290">

## My dashboard 
![Capture d’écran 2024-01-09 à 19 22 51](https://github.com/supabase/supabase/assets/82728820/d2ad9906-c78e-4f36-8cc2-f9abff6cf6a5)

**Comment by lauri865** [comment]
Same problem here. Would love to give this a try, as this (lack of auth customization) has been the #1 missing feature in Supabase for some time now.

**Comment by saltcod** [comment]
https://github.com/supabase/infrastructure/pull/16685

**Comment by J0** [comment]
Hey all,

Thanks for flagging this, the issue arises from a permissions issue and a fix will be going out within the next 24 hours. Sorry for the trouble.

In the meantime if there are any issues or concerns feel free to let us know :)

**Comment by thibault-chausson** [comment]
Thank you very much for your dispatch :)

**Comment by J0** [comment]
Hey Team,

Thanks for your patience. We've deployed the fix to prod and you should be able to attach hooks now. Do let us know if there are any further issues though

Thanks!

**Comment by thibault-chausson** [comment]
Thanks a lot

But I don't understand an error, here is the log returned by the auth logs. It informs me that I don't have access to the public schema, but I have given it the rights, see the code below.

Thank you for your help.

 
```JSON
Log ID
XXXXXXXXX

Log Timestamp (UTC)
2024-01-16T15:44:09.000Z

Log Event Message
{"auth_event":{"action":"login","actor_id":"XXXXXXXXXX","actor_username":"XXXXXXXXX","actor_via_sso":false,"log_type":"account","traits":{"provider":"email"}},"component":"api","error":"ERROR: permission denied for schema public (SQLSTATE 42501)","level":"error","method":"POST","msg":"500: Error invoking access token hook.","path":"/token","referer":"XXXXXXXXXX","remote_addr":"176.170.39.92","time":"2024-01-16T15:44:09Z","timestamp":"2024-01-16T15:44:09Z"}

Log Metadata
[
  {
    "message": null,
    "timestamp": "2024-01-16T15:44:09Z",
    "__MONOTONIC_TIMESTAMP": null,
    "CODE_FUNC": null,
    "instance_id": null,
    "status": null,
    "_CMDLINE": null,
    "method": "POST",
    "_SYSTEMD_CGROUP": null,
    "CODE_FILE": null,
    "EXECUTABLE": null,
    "_EXE": null,
    "UNIT": null,
    "level": "error",
    "_COMM": null,
    "duration": null,
    "issuer": null,
    "_LINE_BREAK": null,
    "_SOURCE_REALTIME_TIMESTAMP": null,
    "msg": "500: Error invoking access token hook.",
    "action": null,
    "login_method": null,
    "_UID": null,
    "host": "db-whqaysgatfhrzrhnvibl",
    "PRIORITY": null,
    "_CAP_EFFECTIVE": null,
    "_PID": null,
    "INVOCATION_ID": null,
    "_SYSTEMD_UNIT": null,
    "source_type": null,
    "SYSLOG_FACILITY": null,
    "request_id": null,
    "CODE_LINE": null,
    "path": "/token",
    "component": "api",
    "project": null,
    "user_id": null,
    "auth_event": [
      {
        "action": "login",
        "actor_id": "XXXXXXXXXX",
        "actor_name": null,
        "actor_username": "XXXXXXXXXX",
        "actor_via_sso": false,
        "log_type": "account",
        "traits": [
          {
            "channel": null,
            "provider": "email",
            "provider_type": null,
            "user_email": null,
            "user_id": null,
            "user_phone": null
          }
        ]
      }
    ],
    "args": [],
    "referer": "XXXXXXXXXX",
    "factor_id": null,
    "provider": null,
    "client_id": null,
    "remote_addr": "176.170.39.92",
    "_SYSTEMD_SLICE": null,
    "_SYSTEMD_INVOCATION_ID": null,
    "header": null,
    "_MACHINE_ID": null,
    "_AUDIT_LOGINUID": null,
    "_TRANSPORT": null,
    "_SELINUX_CONTEXT": null,
    "MESSAGE_ID": null,
    "__REALTIME_TIMESTAMP": null,
    "metadata": [],
    "_STREAM_ID": null,
    "metering": null,
    "time": null,
    "_GID": null,
    "_BOOT_ID": null,
    "SYSLOG_IDENTIFIER": null,
    "_AUDIT_SESSION": null,
    "error": "ERROR: permission denied for schema public (SQLSTATE 42501)"
  }
]
```


My postgresql code

```SQL
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
as $$
   declare
    user_roles text[];
    claims jsonb;
  begin
    -- Get user roles new
    select array_agg(rt.role_type)
    into user_roles
    from public.roles r
    join public.roles_type rt on r.role_id = rt.id
    where r.user_id = event->>'user_id';

    -- Proceed only if the user have roles
    if user_roles is not null then
      claims := event->'claims';

      -- Check if 'user_metadata' exists in claims
      if jsonb_typeof(claims->'user_metadata') is null then
        -- If 'user_metadata' does not exist, create an empty object
        claims := jsonb_set(claims, '{user_metadata}', '{}');
      end if;

      -- Set a claim of roles
      claims := jsonb_set(claims, '{user_metadata, roles}', to_jsonb(user_roles));

      -- Update the 'claims' object in the original event
      event := jsonb_set(event, '{claims}', claims);
    end if;

    -- Return the modified or original event
    return event;
  end;
$$;

grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon;
```

**Comment by J0** [comment]
Hey Thibault,

Thanks for reporting this. There's likely a permissions error on the `public.roles` and `public.role_type` table. You will need to grant `supabase_auth_admin` access to both tables in order for the hook to go through.

```
grant all
  on table public.<your_table_name>
  to supabase_auth_admin;

revoke all
  on table public.<your_table_name>
  from authenticated, anon;
```

We'll see if there's any better way to surface this so that one can view the error more easily

Thanks!

**Comment by ndvb88** [comment]
I still have this issue? Auth still works, but JWT doesn't get updated. I've even tried updating it with static information just to test if I can update the app_metadata or user_metadata but neither works. Any idea what could be the cause?

**Comment by thibault-chausson** [comment]
Can you provide more details, such as your PL/SQL function for customizing the JWT, an example of a decoded JWT ([jwt.io](https://jwt.io)) that you can retrieve using `getUser` or `getSession` (the `access_token`), for your information the `user_metadata` retrieved with getUser or getSession are not modified because they are independent of the JWT.

**Comment by ndvb88** [comment]
@thibault-chausson Thank you for your response. you say:
> for your information the user_metadata retrieved with getUser or getSession are not modified because they are independent of the JWT.
And indeed I see that that appears to explain the issue of me not finding the changes in app_metadata. The changed app_metadata is visible in the JWT but not in const data = await supabase.auth.getUser(). I'm utterly confused by this. Could you point me to a resource that explains how this works? What use is this app_metadata if it is not retreived in getUser()? I want to use it for protecting dynamic routes for multi tenancy and complex RBAC based on manager/employee relations in the database and according to the Supabase docs I should always use getUser() for protecting pages:
> Be careful when protecting pages. The server gets the user session from the cookies, which can be spoofed by anyone.
Always use supabase.auth.getUser() to protect pages and user data.
Your help is much appreciated.

**Comment by thibault-chausson** [comment]
No problem, it's a pleasure to help!

How it works, or at least from what I understand! In your Supabase Dashboard, in the table section: `Auth.users`, you will find a field `raw_user_meta_data` containing various information that is very handy if you use a connection through Google Auth or similar.

![Screenshot 2024-02-13 at 22 08 37](https://github.com/supabase/supabase/assets/82728820/e51f2e03-be0c-4ce6-9fd0-c011a62b622e)

To retrieve your token, you can do so using `getUser` or `getSession`:
```TS
const session = supabase.auth.getSession();
const access_token = session?.access_token
```

Afterward, you can decode it using a [jwt-decode](https://www.npmjs.com/package/jwt-decode) for front-end or a [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) for back-end. For example, for a backend verification (I use NextJS):

# The different possibilities

## Option 1:

I do not want to use `getUser`, as I consider the actions the user will perform are not very sensitive, but I want to verify they have not altered their token.

```TS
import jwt, { JwtPayload } from 'jsonwebtoken';

const SECRET_KEY = process.env.NEXT_PRIVATE_SUPABASE_JWT_SECRET as string;

function verifySupabaseToken(token: string): JwtPayload | null {
  try {
    return jwt.verify(token, SECRET_KEY) as JwtPayload;
  } catch (error) {
    // Manage error
    return null;
  }
}

export async function POST(req: Request) {
  const { token } = await req.json();
  const payload = verifySupabaseToken(token as string);
  // A token payload is a part of a token (like a JWT) that contains information about the user and other data. It is securely encoded in the token and can include details such as the user's ID, roles, permissions, and other custom attributes.
  if (payload) {
    // Return jwt decoded
    return new Response(JSON.stringify({ payload }), { status: 200 });
  } else {
    return new Response('Invalid or expired token', { status: 401 });
  }
}
```

You can check the signature of your token by retrieving the appropriate Key in Supabase, be careful to use it only in the backend for security reasons.

This method allows verifying the user's roles without requiring an authentication request, and I consider that a 24h token (3600sec is secure enough).

## Option 2:

The user wants to perform a very sensitive action, I am in my backend, I request a `getUser` and quickly decode my token with a jwt-decode.

## Option 3:

I think the action is not very sensitive, so in front-end or back-end, I do a `getSession` and a jwt-decode.

# The sensitivity of actions

## Very sensitive

- asking Supabase to delete a user
- assigning roles to users
- ...

## Sensitive

- sending an automatic email

## Not sensitive

- protecting a page
- ...

# Conclusion

Depending on the sensitivity, I use the most appropriate method. A `getUser` makes a call to Supabase, which costs 'money' because the number of authentications is limited.

__It is very important to keep in mind that front-end protections can always be bypassed, so good RLS (Row Level Security) must be implemented.__

If you need help, do not hesitate!

**Comment by ThobyV** [comment]
This still doesn't work I don't know if I am missing something

**Comment by allpwrfulroot** [comment]
> I still have this issue? Auth still works, but JWT doesn't get updated. I've even tried updating it with static information just to test if I can update the app_metadata or user_metadata but neither works. Any idea what could be the cause?

I think I'm seeing this as well: I can add a custom claim on my JWT, and I see it and verify it client-side, but it's no longer present if I surface the claims inside Postgres: `current_setting('request.jwt.claims')::json`

I've tried a few different things, but all have been reset to the static `user` contents when used any Postgres functions:
- custom claim
- app_metadata
- user_metadata

I'm trying to better understand the mechanisms and guardrails for this? I completely understand wanting to limit JWT hacking, security is great. One set of questions I have is around the `public.authorize`  function: the [example and info given](https://supabase.com/docs/guides/auth/custom-claims-and-role-based-access-control-rbac#accessing-custom-claims-in-rls-policies) don't quite make sense. 
- Is there anything special about the name "authorize"? Can it be a different name?
- Why are we passing in the user_id? It's not actually referenced in the example provided

If people know a bit more about how this is set up, I'd love to understand so I can develop a solution for work!

**Comment by thibault-chausson** [comment]
Hey!

First, I have a question: how do you retrieve your JWT in your application? Have you tried decoding your JWT with jwt.io?

**Comment by allpwrfulroot** [comment]
We started with a roundabout way (RPC) before the custom auth hook, and can generate a usable long-lived token with an extra 'oid' (org ID) claim in the payload. This is for an API key, and the presence of the claim works with our Python SDK. We can confirm that the claim exists on the JWT (thx jwt.io) and that it serves as an auth token just fine.

However, now we want to differentiate between SDK calls and web app calls, and that's when we discovered the magical resetting of claims in between SDK operation and Postgres function. Putting in an "authorize" function doesn't appear to alter the magical resetting.

**Comment by wysohn** [comment]
So for anyone who is struggling with a custom auth token trying to use a private schema, make sure that the`supabase_auth_admin` has bypass access for RLS. Or this could apply to `public` schema as well, if something is not configured correctly.

After hours of struggling, I realized that, by directly connecting to the db, the `supabase_auth_admin` did not receive any result from the table while there are clearly data in it.

Then I realized that the `supabase_auth_admin` was not being able to access it due to RLS.

To debug:

1. access directly to the database with `psql` command as `postgres`
2. use `SET ROLE supabase_auth_admin` command to log in as auth admin user
3. Test if any of the tables you are trying to access actually return anything

To fix
1. Obviously, try everything until something returns. In my case, it was RLS, and this can be bypassed by `create policy "some policy name of your choice" on <my custom schema>.<table name> for select using (true)`
2. Or it could be grant issue `grant select on table ...`
3. Or it could be schema access issue `grant usage on schema ...` which is already mentioned in the official example

**Comment by jonra1993** [comment]
> No problem, it's a pleasure to help!
> 
> How it works, or at least from what I understand! In your Supabase Dashboard, in the table section: `Auth.users`, you will find a field `raw_user_meta_data` containing various information that is very handy if you use a connection through Google Auth or similar.
> 
> ![Screenshot 2024-02-13 at 22 08 37](https://private-user-images.githubusercontent.com/82728820/304548951-e51f2e03-be0c-4ce6-9fd0-c011a62b622e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDI3MjgsIm5iZiI6MTcxMzQwMjQyOCwicGF0aCI6Ii84MjcyODgyMC8zMDQ1NDg5NTEtZTUxZjJlMDMtYmUwYy00Y2U2LTlmZDAtYzAxMWE2MmI2MjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAxMDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhM2E4MDk2MzFhYzc5NmI1MjE3NDY3NTkwZGYzYjViNTFhMmU1YjI0MGE2MmRmZTRkMGNjZTYwYTY4ZjEyYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qkkfB746WR74dEoM0ZUbnORQXOzuZBeEWcTzJa2Vxc)
> 
> To retrieve your token, you can do so using `getUser` or `getSession`:
> 
> ```ts
> const session = supabase.auth.getSession();
> const access_token = session?.access_token
> ```
> 
> Afterward, you can decode it using a [jwt-decode](https://www.npmjs.com/package/jwt-decode) for front-end or a [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) for back-end. For example, for a backend verification (I use NextJS):
> 
> # The different possibilities
> ## Option 1:
> I do not want to use `getUser`, as I consider the actions the user will perform are not very sensitive, but I want to verify they have not altered their token.
> 
> ```ts
> import jwt, { JwtPayload } from 'jsonwebtoken';
> 
> const SECRET_KEY = process.env.NEXT_PRIVATE_SUPABASE_JWT_SECRET as string;
> 
> function verifySupabaseToken(token: string): JwtPayload | null {
>   try {
>     return jwt.verify(token, SECRET_KEY) as JwtPayload;
>   } catch (error) {
>     // Manage error
>     return null;
>   }
> }
> 
> export async function POST(req: Request) {
>   const { token } = await req.json();
>   const payload = verifySupabaseToken(token as string);
>   // A token payload is a part of a token (like a JWT) that contains information about the user and other data. It is securely encoded in the token and can include details such as the user's ID, roles, permissions, and other custom attributes.
>   if (payload) {
>     // Return jwt decoded
>     return new Response(JSON.stringify({ payload }), { status: 200 });
>   } else {
>     return new Response('Invalid or expired token', { status: 401 });
>   }
> }
> ```
> 
> You can check the signature of your token by retrieving the appropriate Key in Supabase, be careful to use it only in the backend for security reasons.
> 
> This method allows verifying the user's roles without requiring an authentication request, and I consider that a 24h token (3600sec is secure enough).
> 
> ## Option 2:
> The user wants to perform a very sensitive action, I am in my backend, I request a `getUser` and quickly decode my token with a jwt-decode.
> 
> ## Option 3:
> I think the action is not very sensitive, so in front-end or back-end, I do a `getSession` and a jwt-decode.
> 
> # The sensitivity of actions
> ## Very sensitive
> * asking Supabase to delete a user
> * assigning roles to users
> * ...
> 
> ## Sensitive
> * sending an automatic email
> 
> ## Not sensitive
> * protecting a page
> * ...
> 
> # Conclusion
> Depending on the sensitivity, I use the most appropriate method. A `getUser` makes a call to Supabase, which costs 'money' because the number of authentications is limited.
> 
> **It is very important to keep in mind that front-end protections can always be bypassed, so good RLS (Row Level Security) must be implemented.**
> 
> If you need help, do not hesitate!

Thanks @thibault-chausson for this insight I was expecting to get the claim in the supabase session but It required decoding the JWT token to find it.

<img width="1234" alt="image" src="https://github.com/supabase/supabase/assets/23468720/eba15635-7340-4f92-a8e2-fda7274bfca4">

**Comment by titibudala** [comment]
Is there any way to also update the payload returned by getUser to be the same as the access token? Currently custom claims are present in the token but not in the payload.
Or decoding the jwt is the only workaround for now?

**Comment by thibault-chausson** [comment]
It is impossible to update the payload returned by getUser, for security reasons! The payload of getUser could be altered by a malicious user. This is impossible with a JWT because it is signed! I am not an employee of Supabase, but I believe this policy is implemented to prevent developers from using the getUser payload without ensuring it is properly signed.

**Comment by L-Sypniewski** [comment]
@thibault-chausson thanks for clarifying, I thought C# SDK contains a bug!

Just in case someone unnecessarily tries to implement an Auth Hook  - if you have the information you want to add to user's data during user's creation, you can add it during sign up process and it'll be included in the JWT token.
An example from my C# code:
``cs
            var signUpOptions = new SignUpOptions
            {
                Data = new Dictionary<string, object>
                {
                    { "user_name", RegisterModel.Username }
                }
            };
            var response = await SupabaseClient.Auth.SignUp(RegisterModel.Email, RegisterModel.Password, signUpOptions).ConfigureAwait(false);
``
`user_metadata` from JWT token returned by Supabase:
``json
    "user_metadata": {
      "email": "<email address`",
      "email_verified": false,
      "phone_verified": false,
      "sub": "1e2dabae-2104-421c-a3f9-4bbc7304eb4d",
      "user_name": "john doe"
    },
```
I would assume the same approach works when a user is edited, but haven't checked that.
