### ISSUE TITLE
Supabase cookie sessions clear on browser refresh

### ISSUE THREAD

**Issue by timothyerwin** [supabase/supabase#31112]
I followed the guides for adding Supabase Auth with Google prebuilt and everything works perfect for initial login and subsequent browsing around the authenticated site. However, whenever I refresh the page Supabase immediately clears all the cookies and complains about some PKSE flow or something.

I have all the right middleware and server and client files set exactly as the guides show.

I followed the guides here and am using the Google prebuilt https://supabase.com/docs/guides/auth/social-login/auth-google?queryGroups=environment&environment=client

I can't understand why the code below is trying to get the session from the url when the cookies for Supabase session are there. I'm not using any url flow.

I monkey patched the cookies on the client to figure out where it is getting cleared

<img width="738" alt="Screenshot 2024-12-12 at 5 31 21 PM" src="https://github.com/user-attachments/assets/d4cc3454-b24d-43dd-a9ab-90751ce83d85" />

<img width="851" alt="Screenshot 2024-12-12 at 5 31 48 PM" src="https://github.com/user-attachments/assets/2041bf76-9ccd-4490-997e-bf5d40b2e6ca" />

```
if (typeof window !== 'undefined') {
  const originalCookieDescriptor = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie');
  
  Object.defineProperty(document, 'cookie', {
    get() {
      return originalCookieDescriptor.get.call(this);
    },
    set(value) {
      console.log('Cookie being set:', value);
      // debugger;
      return originalCookieDescriptor.set.call(this, value);
    }
  });
}
```

```javascript
async function handleSignInWithGoogle(response) {
  const { data, error } = await supabase.auth.signInWithIdToken({
    provider: 'google',
    token: response.credential,
  })
}
```

```
    "next": "15.1.0",
    "@supabase/ssr": "^0.5.2",
    "@supabase/supabase-js": "^2.47.6",
```

**Comment by timothyerwin** [comment]
I also tried to do this in the client with no luck

```javascript
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

import { createBrowserClient } from '@supabase/ssr'

export function createClient() {
  return createBrowserClient(
    supabaseUrl,
    supabaseKey, {
      auth: {
        detectSessionInUrl: false,
        persistSession: true,
        autoRefreshToken: true,
      }
    }
  )
}

const supabase = createClient(supabaseUrl, supabaseKey)

export default supabase;
```

**Comment by ergodic1** [comment]
We ran into this issue on production after upgrading to `2.47.6` from `2.47.5`.
A browser refresh button completely wiped the cookies!

Try downgrading while it's being fixed by supabase.

**Comment by timothyerwin** [comment]
> We ran into this issue on production after upgrading to `2.47.6` from `2.47.5`. A browser refresh button completely wiped the cookies!
> 
> Try downgrading while it's being fixed by supabase.

Thanks! Funny thing is I did try the downgrade because I remembered it working but I didn't remove the caret in the version so I think it just did the same latest minor lol

**Comment by alessandrojcm** [comment]
Thanks @ergodic1 I was going crazy for a second wondering why my auth wasn't working all of a sudden :facepalm: For the record I am using Svelte and SvelteKit. I think this should be re-opened as it still does not work.

**Comment by teerzo** [comment]
Im still having this issue with next js/ssr,  when a creating a createBrowserClient on the client side it clears the cookie
