### ISSUE TITLE
Maybe I'm misunderstanding, but there seems to be a discrepancy in the documentation about the 'auth/callback' route

### ISSUE THREAD

**Issue by sglindme** [supabase/supabase#35544]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/server-side/nextjs?queryGroups=router&router=app

## Describe the problem

In the Supabase Vercel starter: https://vercel.com/templates/next.js/supabase
there is a route 'auth/callback'. 
A comment in this file says this:

>   // The `/auth/callback` route is required for the server-side auth flow implemented
>   // by the SSR package. It exchanges an auth code for the user's session.
>   // https://supabase.com/docs/guides/auth/server-side/nextjs

But this 'auth/callback' route is not described anywhere in the supabase doc that is linked by the url

## Describe the improvement

I don't understand if I need that route or not. If I DO need it, then I think it should be explained in the supabase guide at https://supabase.com/docs/guides/auth/server-side/nextjs

## Additional context

I'd also appreciate a response explaining if I need the auth/callback route or not

**Comment by ElectricCodeGuy** [comment]
I implemented an exmaple here you can follow: https://github.com/ElectricCodeGuy/SupabaseAuthWithSSR

In short, you do need it since the auth server need to fetch a api route to get the information it needs

**Comment by sglindme** [comment]
ah this is very nice thank you

**Comment by Hallidayo** [comment]
Going to close this one, Thanks for your help @ElectricCodeGuy !

**Comment by sglindme** [comment]
wait why is this closed? the issue isn't resolved. the documentation guide is incorrect. @Hallidayo

**Comment by Hallidayo** [comment]
Ahh sorry I'll re-open.

**Comment by ElectricCodeGuy** [comment]
> wait why is this closed? the issue isn't resolved. the documentation guide is incorrect. [@Hallidayo](https://github.com/Hallidayo)

That is actually true. Step 5 is wrong.

```
import { login, signup } from './actions'
export default function LoginPage() {
  return (
    <form>
      <label htmlFor="email">Email:</label>
      <input id="email" name="email" type="email" required />
      <label htmlFor="password">Password:</label>
      <input id="password" name="password" type="password" required />
      <button formAction={login}>Log in</button>
      <button formAction={signup}>Sign up</button>
    </form>
  )
}
```

Should be something like

```
import { login } from './actions'
import { useFormStatus } from 'react-dom';

export default function LoginPage() {
  return (
    <form action={login}>
      <label htmlFor="email">Email:</label>
      <input id="email" name="email" type="email" required />
      <label htmlFor="password">Password:</label>
      <input id="password" name="password" type="password" required />
       <SubmitButton />
    </form>
  )
}

function SubmitButton() {
  const { pending } = useFormStatus();

  return (
    <Button
      type="submit"
      disabled={pending}
      className="w-full py-6 font-medium"
    >
      {pending ? <Loader2 className="h-5 w-5 animate-spin" /> : 'Log in'}
    </Button>
  );
}
```

And same logic for the Signup server action.

Also the error page should not have a page.tsx it should just be

/app/login/error.tsx

Documentation: 
https://nextjs.org/docs/app/building-your-application/routing/error-handling 
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations

Rest of the documentation is correct as far as I can tell.

Should I make a pull request with this? @Hallidayo

**Comment by Hallidayo** [comment]
@ElectricCodeGuy sure 100% feel free to!

**Comment by sglindme** [comment]
awesome @ElectricCodeGuy  ty

although don't you also need to add the /auth/callback file to the guide?

**Comment by silentworks** [comment]
The `/auth/callback` isn't necessary for email/password sign-ups/sign-ins. This is only necessary if you are doing OAuth sign-ups/sign-ins. This guide doesn't cover it because this guide is purely for email/password sign-ups/sign-ins. This however is covered in the OAuth guides https://supabase.com/docs/guides/auth/social-login/auth-github?queryGroups=language&language=js&queryGroups=environment&environment=server&queryGroups=framework&framework=nextjs#add-login-code-to-your-client-app which is where It's necessary. The Vercel template you linked to is outdated and used the `/auth/callback` for even email/password but that has it's limitations. There is no PR necessary for the guide you linked to as it serves it's purpose.

**Comment by sglindme** [comment]
The guide I linked to needs to add how to setup the "forgot password" optoin.

And the Vercel template should be updated and not conflict with the guide.

**Comment by silentworks** [comment]
@sglindme your original post didn't ask about "forgot password", I was addressing what you asked about in your original post. For forgot password there is another guide for that https://supabase.com/docs/guides/auth/passwords?queryGroups=language&language=js&queryGroups=flow&flow=pkce&queryGroups=framework&framework=nextjs#resetting-a-password but I think you are more looking for a complete tutorial on all the Auth related flows.

The Vercel template should be updated indeed.

**Comment by cekuu35** [comment]
The /auth/callback route IS needed for OAuth flows (Google, GitHub, etc.) but NOT for email/password. The Vercel template includes it for OAuth support, but the Supabase Next.js guide only covers email/password — hence the discrepancy.

For email/password: no /auth/callback needed — supabase-js handles code exchange internally.

For OAuth: you need /auth/callback that calls exchangeCodeForSession(code). The OAuth guides cover this: https://supabase.com/docs/guides/auth/social-login/auth-github

Suggested doc fix: add a note in the Next.js SSR guide linking to the OAuth guide for the callback route, and clarify it's only for OAuth.
