### ISSUE TITLE
Logging in with Facebook gives 502 error

### ISSUE THREAD

**Issue by fabianmossberg** [supabase/supabase#4758]
# Bug report

Facebook login gives 502 error when being set up according to the documentation.

## Describe the bug

Following the instructions on:
https://supabase.com/docs/guides/auth/auth-facebook

When running the following code:

```js
const { user, session, error } = await supabase.auth.signIn({
  provider: 'facebook'
})
```

I get sent to `https://[my-project].supabase.co/auth/v1/authorize?provider=facebook` that gives me 502, bad gateway from Cloudflare.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new Facebook app
2. Enter your Facebook apps ID and Secret to Supabase.
3. Add you supabase, url + `/auth/v1/callback/` as **Valid OAuth Redirect URIs** in your Facebook app.
4. Run the following code

```js
const { user, session, error } = await supabase.auth.signIn({
  provider: 'facebook'
})
```

## Expected behavior

I would have to accept connecting with Facebook.

## Screenshots

<img width="901" alt="Screenshot 2022-01-01 at 21 46 08" src="https://user-images.githubusercontent.com/1999142/147859918-7585dc83-92f6-4cb6-9543-aafda3dfaf21.png">

## System information

- OS: MacOS
- Browser: All
- Version of supabase-js: 1.29.1
- Version of Node.js: 16.13.1

**Comment by kangmingtay** [comment]
Hi @fabianmossberg, was there an error message displayed in the url / response in addition to the 502 error?

**Comment by fabianmossberg** [comment]
@kangmingtay: no, no specific error in the response or in the logs at supabase.

**Comment by bokub** [comment]
I have the same problem with the **GitHub** and **Google** providers, so I'm not sure it's linked to Facebook.

I have 2 projects on Supabase, but only one of them has this issue (it used to work before).

I have restarted the server multiple times and it didn't fix the issue.

This is a screenshot of `https://[project-id].supabase.co/auth/v1/authorize?provider=github&redirect_to=http%3A%2F%2Flocalhost%3A3000%2Flogin`


![image](https://user-images.githubusercontent.com/17952318/148048603-2e855062-5eeb-4b46-b9d9-879f27ffac66.png)

**Comment by kangmingtay** [comment]
Hi @fabianmossberg and @bokub, could you guys please email support@supabase.io so i can look into the issue? Thanks!

**Comment by bokub** [comment]
Done :heavy_check_mark:

**Comment by bokub** [comment]
**Update**: the URL now shows this raw JSON instead of the 502 Cloudflare error page:

```json
{"message": "An invalid response was received from the upstream server"}
```

The response code is still 502 though.

**Comment by kangmingtay** [comment]
hi @bokub, we're still investigating your project, so far, it seems like this is an issue with gotrue not being able to connect to the db and not an oauth issue, will update you via email when this is resolved!

**Comment by bokub** [comment]
The problem seems fixed! (on my side) :tada:

**Comment by chipilov** [comment]
I am currently experiencing a similar issue when trying to sign-up new users using supabase.auth.signup() with E-mail auth. The response I get is 502:
```
{
  "message":"An invalid response was received from the upstream server"
}
```

**Comment by kiwicopple** [comment]
hey @chipilov can you please open a ticket on https://app.supabase.com/support/new ? We can check if it's your specific instance

**Comment by chipilov** [comment]
@kiwicopple Yep, already opened one, just wanted to mention it here, too in case it's helpful for the investigation.

**Comment by chipilov** [comment]
In my case, it seems like the culprit is custom SMTP - as soon as I enable it, I start getting the error and then even if I disable custom SMTP, I continue getting the error.

@kiwicopple Should I open a separate issue for this?

**Comment by pixelsaurus** [comment]
I am also experiencing this error when attempting to use only Phone auth as the signIn/signUp method.

**Comment by bokub** [comment]
So, the problem was fixed last week, but it appeared again...

I now have the following 502 error (exactly like last time):

```json
{
  "message":"An invalid response was received from the upstream server"
}
```

**Comment by kangmingtay** [comment]
Hey @bokub, we're looking into this now, in the meantime, if anyone's still experiencing this issue, please email support. You can find the link to our email support here! (https://supabase.com/support)

**Comment by simpautus** [comment]
Having the same problem. Getting 502 response to auth requests (Email signin/signup, Magic link, Github, Facebook, Google). Auth works normally pointed to another fresh Supabase backend.

`{
  "message":"An invalid response was received from the upstream server"
}`

**Comment by kangmingtay** [comment]
hi @simpautus, please email support with your project ref so we can debug it and get it fixed for you!

**Comment by simpautus** [comment]
> hi @simpautus, please email support with your project ref so we can debug it and get it fixed for you!

I did. Update here too that email auth worked when creating a fresh Supabase project but without additional changes all auth calls stopped working (same 502 response) after switching on the Github OAuth. Switching it back off doesn't fix the issue but still all auth calls fail. I get the same response calling the API directly without the library. Other endpoints but auth give a 200 OK response.

**Comment by simpautus** [comment]
I think issue in my case was caused by me truncating data from auth schema by sql script (I had a "reset" create script for dev purposes that also drops objects before creating them and truncates data). Now I have a fresh instance with altered scripts and so far it's working as expected.

**Comment by devdev-dev** [comment]
I have the same problem while using the magiclink and opened a ticket as well.

**Comment by mbalslow** [comment]
I have the same (or very similar) issue with the Azure provider: https://github.com/supabase/supabase/discussions/5261

I also reached out to support via email.

**Comment by bosaengineering** [comment]
I have the same issue as well with Google. I also have reached out to support via email.

**Comment by tocteman** [comment]
Same thing happening with Facebook (Google's working fine). Thanks for your help.

**Comment by chipilov** [comment]
@dthyresson Maybe this issue should be re-opened - multiple people are still reporting it and the team might not have visibility that it still exists.

**Comment by izqalan** [comment]
Having the same problem but only on React Native & using email auth.

**Comment by OsmnShkh** [comment]
Having the same issue here, with Google OAuth.

**Comment by kangmingtay** [comment]
hi @OsmnShkh, please email support@supabase.com with your project reference so we can triage your issue.

**Comment by OsmnShkh** [comment]
@kangmingtay Will do, thanks.

**Comment by bhagavan44** [comment]
I have same problem with google authentication

**Comment by codeofsumit** [comment]
We are seeing the same error with Facebook. People can't sign up using facebook due to this error

```
{
  "message":"An invalid response was received from the upstream server"
}
```

**Comment by J0** [comment]
Hey all,

We will be closing this issue since it represents a class of issues rather than a single specific issue and we would be able to best track and handle issues via our support channel.  As such, reach out to support@supabase.com if you are still facing OAuth related issues.

For even faster resolution, do check out our [Logs explorer]
(https://supabase.com/docs/guides/platform/logs) and view the Auth logs.  Sometimes the issue could be a simple one(like a permissions error) which can be resolved within seconds! 

If there are any further concerns or questions feel free to leave a comment below and we'll try to get back as soon as we can.

**Comment by susemi99** [comment]
I had a user-related `View` in the Table Editor that I had created as a test, and when I deleted it, the login worked fine.

**Comment by ed-zitle** [comment]
Still having this error with Google login

**Comment by kangmingtay** [comment]
@ed-zitle can you reach out to us at https://app.supabase.com/support/new please?

**Comment by kangmingtay** [comment]
as @J0 mentioned in [this comment](https://github.com/supabase/supabase/issues/4758#issuecomment-1186733704), this error represents a class of issues

it would be a much more efficient use of time for everyone if you reach out to https://supabase.help/ and describe the issue you're facing - please make sure you've checked your [project's auth logs](https://supabase.com/dashboard/project/_/logs/auth-logs) too since that will contain useful information as to why a 502 is being returned.

for the self-hosted folks, you can check the logs in your docker container running the auth service to see why a 502 is being returned

i'll be locking this conversation from now on to prevent this comment from being lost
