### ISSUE TITLE
timestamp type value missing 'Z' in HTTP GET requests

### ISSUE THREAD

**Issue by hyunbinseo** [supabase/supabase#4803]
# Bug report

## Describe the bug

Values of type `timestamp` is formatted as `YYYY-MM-DDTHH:mm:ss.sssZ` as shown in the table editor.

This matches the ISO 8601 format, and are in UTC time-zone (according to the trailing `Z`).

However, in HTTP GET requests
- Trailing `Z` is always trimmed
- If the `.sssZ` value is `.000Z`, `000Z` is trimmed

| Table editor | GET request |
| -- | -- |
| `2022-01-05T00:00:00.001Z` | `2022-01-05T00:00:00.001` |
| `2022-01-05T00:00:00.000Z` | `2022-01-05T00:00:00` |

## Expected behavior

`.sssZ` of timestamp values should not be modified or trimmed.

## To Reproduce

```
// Request
curl -X POST 'https://SUBDOMAIN.supabase.co/rest/v1/users' \
-H "apikey: SUPABASE_KEY" \
-H "Authorization: Bearer SUPABASE_KEY" \
-H "Content-Type: application/json" \
-H "Prefer: return=representation" \
-d '{"id":"A","expires_at":"2022-01-05T00:00:00.001Z"}' // timestamp with .001Z

// Response
[
  {
    "id": "A",
    "created_at": "2022-01-05T06:00:47.37824",
    "expires_at": "2022-01-05T00:00:00.001" // Z is trimmed
  }
]

// Table editor
2022-01-05T00:00:00.001Z
```

```
// Request
curl -X POST 'https://SUBDOMAIN.supabase.co/rest/v1/users' \
-H "apikey: SUPABASE_KEY" \
-H "Authorization: Bearer SUPABASE_KEY" \
-H "Content-Type: application/json" \
-H "Prefer: return=representation" \
-d '{"id":"B","expires_at":"2022-01-05T00:00:00.000Z"}' // timestamp with .000Z

// Response
[
  {
    "id": "B",
    "created_at": "2022-01-05T05:58:31.230597",
    "expires_at": "2022-01-05T00:00:00" // .000Z is trimmed
  }
]

// Table editor
2022-01-05T00:00:00.000Z
```

**Comment by kiwicopple** [comment]
Supabase really leaves all validation to Postgres. For example, if I run this:

```sql
create table test_table (
  id serial primary key,
  test_timestamp timestamp
);

insert into test_table (test_timestamp)
values ('2022-01-05T00:00:00.001Z');

select * from test_table;
```

I get no errors - 

```md
| id | test_timestamp           |
| -- | ------------------------ |
| 1  | 2022-01-05T00:00:00.001Z |
```

If I understand your question (by the title), you'd prefer us to reject this `insert`? However, that would require a change in Postgres default behaviour

**Comment by steve-chavez** [comment]
I don't have the exact snippet, but looks this could be done with a custom domain like:

```sql
CREATE DOMAIN strict_timestamp AS TEXT
CHECK ( no_timezone_included( value ) );

CREATE OR REPLACE FUNCTION no_timezone_included( val TEXT ) RETURNS BOOLEAN as $$
-- ..complete the body here
$$ language plpgsql STABLE;
```

You can follow the idea on this [blog post](https://justatheory.com/2007/11/postgres-timezone-validation/) to complete the function.

Then the `expired_at` column could use this domain as the type instead of the default `timestamp`.

**Comment by hyunbinseo** [comment]
@kiwicopple I was hoping for a more consistent behavior.

According to https://github.com/supabase/supabase/discussions/2839, users are using `new Date().toISOString()` to generate Postgres timestamp values (not timestamptz).

Since this method returns a `YYYY-MM-DDTHH:mm:ss.sssZ` formatted string - a format also used in the Supabase table editor's `timestamp` type - only allowing one of the following formats in `GET(select)` and `POST(insert)` seems more consistent.

- `YYYY-MM-DDTHH:mm:ss.sssZ` (ISO 8601 with UTC time zone)
- `YYYY-MM-DD HH:mm:ss` ([PostgreSQL](https://www.postgresql.org/docs/current/datatype-datetime.html)'s `timestamp with time zone`)
- other relevant formats

**Comment by egor-romanov** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since (I tried to reproduce, but i see all the correct values in supabase table editor or when querying with psql).
<img width="497" alt="image" src="https://github.com/supabase/supabase/assets/58992960/17f6bce9-731f-48d9-ae8a-3c45255ea3b4">
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and it.
Cheers!

**Comment by ItayElgazar** [comment]
Z s still trimmed

**Comment by opgbaudouin** [comment]
It seems when using TimestampZ Supabase API is returning a 'minimum' size format for the ISO string. 

i.e. 

whereas iso might be:

2014-03-12T00:15:33.600+00:00

the api returns

2014-03-12T00:15:33.6+00:00  

Which makjes for horrific parsing - there is no downside (Except a few bytes) to stick to the complete ISO format. (I'm ignoring Z or +00:00 as both are fine)

It should be a setting inside the supabase api HOW you want dates/time to be returned as this is such a common thing.

**Comment by TalkSimple** [comment]
Hello. We need this badly. Our system shows datetimes locally for each user. It also allows clients to integrate. And while our documentation clearly says use +0UTC timestamp values, integrations are being set up with all kinds of values.

It makes it look like our app is messing up the dates, but we simply have multiple 3rd parties using different time zones all over the place.

It would be great to enforce +0 UTC.

As the original poster said
If      'YYYY-MM-DDTHH:mm:ss.sss' failed 
BUT 'YYYY-MM-DDTHH:mm:ss.sssZ' passed (With Z)

This would avoid bad data entering the database to begin with. Once it is in the database, we have no way to know the original timezone.

If there is a chance to address this in anyway I would be very grateful!

**Comment by steve-chavez** [comment]
There's now a way to specify the client timezone per-request with [Prefer: timezone](https://docs.postgrest.org/en/v14/references/api/preferences.html#prefer-timezone), I believe this should solve all issues here.

This functionality is still not exposed through the client libraries though, so you should request it in https://github.com/supabase/supabase-js/.
